### Registre d'usuari
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "username": "testUser2",
  "password": "testPassword2"
}

### Login d'usuari
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "username": "testUser2",
  "password": "testPassword2"
}


### Obtenir libros (token)
GET http://localhost:3000/api/v1/books
Authorization: Bearer {eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyMiIsImlhdCI6MTczMDkxNzk5MSwiZXhwIjoxNzMwOTE4NTkxfQ.nmP_2rD0vTWUUuRQWWRl4j2k9H2t917MYvnTWZwGVw8}